name: zsystem-member-updater
run-name: ${{ github.actor }} is updating all ZSystem members

on:
  workflow_dispatch:
    paths:
      - wiki/**
      - .github/workflows/update-zsystem-members.yml

concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write

jobs:
  update-zsystem-members:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1.1.5
      - name: Update app
        run: |
          steamcmd +force_install_dir ~/.steam/steam/steamapps/common/Valheim +login anonymous +app_update 896660 validate +quit
      - name: Update members
        run: ./AssemblyMemberGetter.exe ~/.steam/steam/steamapps/common/Valheim/valheim_server_Data/Managed/assembly_valheim.dll ./wiki/ -i ZSFX,ZSocket,ZSocket2,ZSteamMatchmaking,ZSteamSocket,ZSteamSocketOLD,ZPlayFabLobbySearch,ZPlayFabMatchmakeLobbyLeftCallback,ZPlayFabMatchmakeServerStarted,ZPlayFabMatchmakeServerStopped,ZPlayFabMatchmaking,ZPlayFabMatchmakingFailedCallback,ZPlayFabMatchmakingFailReason,ZPlayFabMatchmakingSuccessCallback,ZPlayFabSocket,ZPlayFabSocketState,ZNat,ZNet,ZNetPeer,ZNetScene,ZNetStats,ZNetView,ZNtp,ZDO,ZDOID,ZDOMan,ZDOPool,ZDOPeer,ZRoutedRpc,RoutedRPCData,ZRpc,ZPackage,ZSyncAnimation,ZSyncTransform
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
